#!/usr/bin/env bash
[ -f index.txt ] && rm index.txt

set -eo pipefail

BIN_DIR=$(cd $(dirname $0); pwd)
ROOT_DIR=$BIN_DIR
PERL=`which perl`
echo "$POST_DIR"

echo "">list 
for f in $(find $1 -name "*.txt")
do
echo "- ["$(head -n 1 $f | sed 's/# //g')"]("$f")" >> list
done

echo "# Index"> index.txt 
sed 's/.txt/.html/g' list >> index.txt

#rm list.txt

MARKDOWN_FILES=`find $1 -name "*.txt"`
touch index.html
LAST="index.html"
NEXT=" "

for f in $MARKDOWN_FILES; do
  
  NEWFILE=${f%.*}.html
  TITLE=$(head -n 1 $f | sed 's/# //g')
  
  NEXT=`basename "$f" .txt`.html
  BUF=$(cat $LAST)
  echo $BUF | sed 's/NEXT/'"$NEXT"'/g' >  $LAST
  
  echo "       $f -> $NEWFILE $TITLE $LAST"
  
  cat $ROOT_DIR/includes/header.html | sed 's/P_TITLE/'"$TITLE"'/g' > $NEWFILE
  $PERL $ROOT_DIR/Markdown.pl $f >> $NEWFILE
  cat $ROOT_DIR/includes/footer.html | sed 's/LAST/'"$LAST"'/g' >> $NEWFILE

  LAST=`basename "$f" .txt`.html
  #rm $f
done 

git add -A . 
git commit -m "Updated" 
git push --all --force
