#!/usr/bin/env bash
[ -f index.txt ] && rm index.txt

set -eo pipefail

BIN_DIR=$(cd $(dirname $0); pwd)
ROOT_DIR=$BIN_DIR
PERL=`which perl`


for f in *.txt
do
echo "- ["$(head -n 1 $f | sed 's/# //g')"]("$f")" >> list.txt
done
echo "# Index"> index.txt 
sed 's/.txt/.html/g' list.txt >> index.txt
rm list.txt

MARKDOWN_FILES=`find $1 -name "*.txt"`

for f in $MARKDOWN_FILES; do
  NEWFILE=${f%.*}.html
  TITLE=$(head -n 1 $f | sed 's/# //g')
  echo "       $f -> $NEWFILE $TITLE"
  echo -e "<html>\n<body>" > $NEWFILE
  cat  $ROOT_DIR/includes/header.html | sed 's/P_TITLE/'"$TITLE"'/g' >> $NEWFILE
  $PERL $ROOT_DIR/Markdown.pl $f >> $NEWFILE
  cat  $ROOT_DIR/includes/footer.html >> $NEWFILE
  echo -e "</body>\n</html>" >> $NEWFILE
  ## rm $f
done 

